name: learning
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # application icon and splash
  flutter_native_splash: ^2.1.6


  cupertino_icons: ^1.0.2

  dartz: ^0.10.1
  get: ^4.6.6
  dio: ^5.4.3+1
  font_awesome_flutter: ^10.8.0
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  cached_network_image: ^3.4.0
  wc_form_validators: ^1.0.1
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.1
  google_fonts: ^6.2.1
  waterfall_flow: ^3.1.0
  nb_utils: ^7.0.3
  flutter_switch: ^0.3.2
  flutter_animate: ^4.3.0
  lottie: any
  web_socket_channel: ^3.0.2
  connectivity_plus: ^6.1.4

  # Map
  flutter_map_location_marker: ^9.0.0
  geolocator: ^12.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

  # Firebase
  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.0
  firebase_analytics: ^11.3.0
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/image/splash.png"
  android: true
  ios: true
  android_12:
    image: "assets/image/splash.png"
  web: false

flutter:

  uses-material-design: true


  assets:
    - assets/translation/
    - assets/image/
    - assets/svg/
    - assets/icon/
    - assets/font/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: shu
      fonts:
        - asset: assets/font/s1.ttf
        - asset: assets/font/s2.ttf
        - asset: assets/font/s3.ttf
        - asset: assets/font/s4.ttf
        - asset: assets/font/s5.ttf
        - asset: assets/font/s6.ttf
        - asset: assets/font/s7.ttf
        - asset: assets/font/s8.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
