name: client
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.6

  dartz: ^0.10.1
  get: ^4.7.2
  dio: ^5.8.0+1
  font_awesome_flutter: ^10.8.0
  flutter_svg: ^2.1.0
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  wc_form_validators: ^1.1.0
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  google_fonts: ^6.2.1
  waterfall_flow: ^3.1.1
  nb_utils: ^7.1.4
  lottie: ^3.3.1
  flutter_animate: ^4.5.2
  flutter_switch: ^0.3.2
  web_socket_channel: ^3.0.3
  connectivity_plus: ^6.1.4

  # MAP
  flutter_map_location_marker: ^10.1.0
  geolocator: ^14.0.1
  flutter_map: ^8.1.1
  latlong2: ^0.9.1


  # Firebase
  firebase_core: ^3.14.0
  firebase_messaging: ^15.2.7
  flutter_local_notifications: ^19.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21


flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/image/splash.png"
  android: true
  ios: true
  android_12:
    image: "assets/image/splash.png"
  web: false


flutter:

  uses-material-design: true

  assets:
    - assets/translation/
    - assets/image/
    - assets/svg/
    - assets/icon/
    - assets/font/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: shu
      fonts:
        - asset: assets/font/s1.ttf
        - asset: assets/font/s2.ttf
        - asset: assets/font/s3.ttf
        - asset: assets/font/s4.ttf
        - asset: assets/font/s5.ttf
        - asset: assets/font/s6.ttf
        - asset: assets/font/s7.ttf
        - asset: assets/font/s8.ttf
